### ISSUE TITLE
anh

### ISSUE THREAD

**Issue by trungduongmewmew** [trungduongmewmew/Install_Jenkins#1]

**Comment by trungduongmewmew** [comment]
<img width="831" alt="1" src="https://github.com/user-attachments/assets/653ee5a0-5984-4e42-b130-6077f6c34a59">

**Comment by trungduongmewmew** [comment]
<img width="922" alt="2" src="https://github.com/user-attachments/assets/7978b795-d942-490b-b9c8-a1bdaaddb742">

**Comment by trungduongmewmew** [comment]
<img width="938" alt="3" src="https://github.com/user-attachments/assets/d1fb0c35-b72d-4c8e-ba5b-6a0443fb97ea">

**Comment by trungduongmewmew** [comment]
<img width="935" alt="8" src="https://github.com/user-attachments/assets/26e78af4-709b-4d4d-837a-04231749bdf2">

**Comment by trungduongmewmew** [comment]
<img width="935" alt="8" src="https://github.com/user-attachments/assets/342fa467-75bd-454c-9296-bc53e55f33df">

**Comment by chauvoba** [comment]
please english me no know vietnamese ty
